' ******************************************************************************
' swxJRNL.swj - journal recorded on 01/29/04 by ALEXIS
' *****************************************************************************
Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long
Dim Annotation As Object
Dim Gtol As Object
Dim DatumTag As Object
Dim FeatureData As Object
Dim Feature As Object
Dim Component As Object
Sub main()

Set swApp = Application.SldWorks

Set Part = swApp.OpenDoc4 ("E:\TP Labo MPSI\Supports\Doshydro\Maquette numérique\Crosse assemblée.SLDASM", 2, 0, "", longstatus)
Set Part = swApp.ActivateDoc ("Crosse assemblée.SLDASM")
swApp.ActiveDoc.ActiveView.FrameWidth = 1205
swApp.ActiveDoc.ActiveView.FrameHeight = 896
swApp.LoadFile2 "E:\TP Labo MPSI\Supports\Doshydro\Maquette numérique\roue_axe.SLDASM", ""
Set Part = swApp.ActiveDoc
Set Part = swApp.OpenDoc4 ("E:\TP Labo MPSI\Supports\Doshydro\Maquette numérique\roue_axe.SLDASM", 2, 0, "", longstatus)
Set Part = swApp.ActivateDoc ("roue_axe.SLDASM")
swApp.ActiveDoc.ActiveView.FrameWidth = 1205
swApp.ActiveDoc.ActiveView.FrameHeight = 896
swApp.LoadFile2 "E:\TP Labo MPSI\Supports\Doshydro\Maquette numérique\Carter_assemblé.SLDASM", ""
Set Part = swApp.ActiveDoc
Set Part = swApp.OpenDoc4 ("E:\TP Labo MPSI\Supports\Doshydro\Maquette numérique\Carter_assemblé.SLDASM", 2, 0, "", longstatus)
Set Part = swApp.ActivateDoc ("Carter_assemblé.SLDASM")
swApp.ActiveDoc.ActiveView.FrameWidth = 1205
swApp.ActiveDoc.ActiveView.FrameHeight = 896
swApp.LoadFile2 "E:\TP Labo MPSI\Supports\Doshydro\Maquette numérique\noix.SLDPRT", ""
Set Part = swApp.ActiveDoc
Set Part = swApp.OpenDoc4 ("E:\TP Labo MPSI\Supports\Doshydro\Maquette numérique\noix.SLDPRT", 1, 0, "", longstatus)
Set Part = swApp.ActivateDoc ("noix.SLDPRT")
swApp.ActiveDoc.ActiveView.FrameWidth = 1205
swApp.ActiveDoc.ActiveView.FrameHeight = 896
swApp.ArrangeWindows 1
swApp.ActiveDoc.ActiveView.FrameWidth = 609
swApp.ActiveDoc.ActiveView.FrameHeight = 448
swApp.LoadFile2 "E:\TP Labo MPSI\Supports\Doshydro\Maquette numérique\piston_doigt.SLDASM", ""
Set Part = swApp.ActiveDoc
Set Part = swApp.OpenDoc4 ("E:\TP Labo MPSI\Supports\Doshydro\Maquette numérique\piston_doigt.SLDASM", 2, 0, "", longstatus)
Set Part = swApp.ActivateDoc ("piston_doigt.SLDASM")
swApp.ActiveDoc.ActiveView.FrameWidth = 1205
swApp.ActiveDoc.ActiveView.FrameHeight = 896
swApp.ArrangeWindows 1
swApp.ActiveDoc.ActiveView.FrameWidth = 609
swApp.ActiveDoc.ActiveView.FrameHeight = 448
swApp.LoadFile2 "C:\Program Files\SolidWorks EE 2002-2003\data\templates\Assemblage.asmdot", ""
Set Part = swApp.ActiveDoc
Set Part = swApp.NewDocument ("C:\Program Files\SolidWorks EE 2002-2003\data\templates\Assemblage.asmdot", 0, 0.000000, 0.000000)
Set Part = swApp.ActivateDoc ("Assem1")
swApp.ActiveDoc.ActiveView.FrameWidth = 1205
swApp.ActiveDoc.ActiveView.FrameHeight = 896
Part.SaveAs2 "E:\TP Labo MPSI\Supports\Doshydro\Maquette numérique\Piston sans mobilité.SLDASM", 0, FALSE, FALSE
swApp.ArrangeWindows 1
swApp.ActiveDoc.ActiveView.FrameWidth = 609
swApp.ActiveDoc.ActiveView.FrameHeight = 298
Set Part = swApp.ActivateDoc ("piston_doigt.SLDASM")
boolstatus = Part.Extension.SelectByID("piston_doigt.SLDASM", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Set Part = swApp.ActivateDoc ("Piston sans mobilité.SLDASM")
Set Part = swApp.ActivateDoc ("roue_axe.SLDASM")
boolstatus = Part.Extension.SelectByID("roue_axe.SLDASM", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Set Part = swApp.ActivateDoc ("Piston sans mobilité.SLDASM")
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
Part.ActiveView().RotateAboutCenter 0.0329538, -0.014994
Part.ActiveView().RotateAboutCenter 0.0329538, -0.014994
Part.ActiveView().RotateAboutCenter 0.0197723, -0.00749698
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, 0.0224909
Part.ActiveView().RotateAboutCenter 0.0197723, 0.0449819
Part.ActiveView().RotateAboutCenter 0.0395445, 0.0824668
Part.ActiveView().RotateAboutCenter 0.0395445, 0.0599759
Part.ActiveView().RotateAboutCenter 0.026363, 0.0599759
Part.ActiveView().RotateAboutCenter 0.0197723, 0.0299879
Part.ActiveView().RotateAboutCenter 0.0131815, 0.0449819
Part.ActiveView().RotateAboutCenter 0.0131815, 0.0224909
Part.ActiveView().RotateAboutCenter 0.0131815, 0.0299879
Part.ActiveView().RotateAboutCenter 0.0131815, 0.014994
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter 0.026363, 0.0299879
Part.ActiveView().RotateAboutCenter 0.0197723, 0.014994
Part.ActiveView().RotateAboutCenter 0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0329538, 0.014994
Part.ActiveView().RotateAboutCenter 0.026363, 0.014994
Part.ActiveView().RotateAboutCenter 0.0395445, 0.0224909
Part.ActiveView().RotateAboutCenter 0.0461353, 0.0299879
Part.ActiveView().RotateAboutCenter 0.0593168, 0.0299879
Part.ActiveView().RotateAboutCenter 0.0329538, 0.0224909
Part.ActiveView().RotateAboutCenter 0.0329538, 0.00749698
Part.ActiveView().RotateAboutCenter 0.026363, 0.00749698
Part.ActiveView().RotateAboutCenter 0.026363, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0395445, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0329538, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0329538, 0.014994
Part.ActiveView().RotateAboutCenter 0.0197723, 0
Part.ActiveView().RotateAboutCenter 0.0395445, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0197723, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0461353, 0.00749698
Part.ActiveView().RotateAboutCenter 0.026363, 0
Part.ActiveView().RotateAboutCenter 0.052726, 0.014994
Part.ActiveView().RotateAboutCenter 0.0329538, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0461353, 0
Part.ActiveView().RotateAboutCenter 0.0329538, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0461353, 0.0224909
Part.ActiveView().RotateAboutCenter 0.0197723, 0.00749698
Part.ActiveView().RotateAboutCenter 0.052726, 0.0299879
Part.ActiveView().RotateAboutCenter 0.0197723, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0395445, 0.0224909
Part.ActiveView().RotateAboutCenter 0.026363, 0.014994
Part.ActiveView().RotateAboutCenter 0.0197723, 0.014994
Part.ActiveView().RotateAboutCenter 0.0461353, 0.0224909
Part.ActiveView().RotateAboutCenter 0.0197723, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0197723, 0.014994
Part.ActiveView().RotateAboutCenter 0.026363, 0.014994
Part.ActiveView().RotateAboutCenter 0.0329538, 0.0224909
Part.ActiveView().RotateAboutCenter 0.052726, 0.0224909
Part.ActiveView().RotateAboutCenter 0.0461353, 0.0299879
Part.ActiveView().RotateAboutCenter 0.0395445, 0.014994
Part.ActiveView().RotateAboutCenter 0.0329538, 0.0299879
Part.ActiveView().RotateAboutCenter 0.0461353, 0.014994
Part.ActiveView().RotateAboutCenter 0.0131815, 0.014994
Part.ActiveView().RotateAboutCenter 0.0461353, 0.0299879
Part.ActiveView().RotateAboutCenter 0.0329538, 0.014994
Part.ActiveView().RotateAboutCenter 0.0395445, 0.0299879
Part.ActiveView().RotateAboutCenter 0.0197723, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0329538, 0.0224909
Part.ActiveView().RotateAboutCenter 0.0197723, 0.014994
Part.ActiveView().RotateAboutCenter 0.026363, 0.014994
Part.ActiveView().RotateAboutCenter 0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ActiveView().RotateAboutCenter 0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.0197723, -0.0224909
Part.ActiveView().RotateAboutCenter -0.0856798, -0.0449819
Part.ActiveView().RotateAboutCenter -0.0593168, -0.0449819
Part.ActiveView().RotateAboutCenter -0.125224, -0.0749698
Part.ActiveView().RotateAboutCenter -0.0856798, -0.0749698
Part.ActiveView().RotateAboutCenter -0.118634, -0.0974608
Part.ActiveView().RotateAboutCenter -0.0395445, -0.0224909
Part.ActiveView().RotateAboutCenter -0.0988613, -0.0824668
Part.ActiveView().RotateAboutCenter -0.0659075, -0.0599759
Part.ActiveView().RotateAboutCenter -0.0593168, -0.0449819
Part.ActiveView().RotateAboutCenter -0.0461353, -0.0299879
Part.ActiveView().RotateAboutCenter -0.026363, -0.014994
Part.ActiveView().RotateAboutCenter -0.0329538, -0.014994
Part.ActiveView().RotateAboutCenter -0.0724983, -0.0299879
Part.ActiveView().RotateAboutCenter -0.0659075, -0.0374849
Part.ActiveView().RotateAboutCenter -0.0593168, -0.0224909
Part.ActiveView().RotateAboutCenter -0.079089, -0.0449819
Part.ActiveView().RotateAboutCenter -0.052726, -0.0224909
Part.ActiveView().RotateAboutCenter -0.0461353, -0.0224909
Part.ActiveView().RotateAboutCenter -0.0395445, -0.014994
Part.ActiveView().RotateAboutCenter -0.0197723, -0.00749698
Part.ActiveView().RotateAboutCenter -0.0395445, -0.014994
Part.ActiveView().RotateAboutCenter -0.026363, -0.014994
Part.ActiveView().RotateAboutCenter -0.0197723, -0.014994
Part.ActiveView().RotateAboutCenter -0.0461353, -0.0224909
Part.ActiveView().RotateAboutCenter -0.026363, -0.0224909
Part.ActiveView().RotateAboutCenter -0.0197723, -0.00749698
Part.ActiveView().RotateAboutCenter -0.0724983, -0.0449819
Part.ActiveView().RotateAboutCenter -0.0329538, -0.014994
Part.ActiveView().RotateAboutCenter -0.0461353, -0.0299879
Part.ActiveView().RotateAboutCenter -0.026363, -0.0224909
Part.ActiveView().RotateAboutCenter -0.0395445, -0.0224909
Part.ActiveView().RotateAboutCenter -0.026363, -0.014994
Part.ActiveView().RotateAboutCenter -0.0197723, -0.014994
Part.ActiveView().RotateAboutCenter -0.0197723, -0.014994
Part.ActiveView().RotateAboutCenter -0.0329538, -0.0299879
Part.ActiveView().RotateAboutCenter -0.0395445, -0.014994
Part.ActiveView().RotateAboutCenter -0.026363, -0.0224909
Part.ActiveView().RotateAboutCenter -0.0395445, -0.0299879
Part.ActiveView().RotateAboutCenter -0.052726, -0.0449819
Part.ActiveView().RotateAboutCenter -0.0593168, -0.0599759
Part.ActiveView().RotateAboutCenter -0.0922706, -0.0899638
Part.ActiveView().RotateAboutCenter -0.0659075, -0.0749698
Part.ActiveView().RotateAboutCenter -0.0593168, -0.0749698
Part.ActiveView().RotateAboutCenter -0.0461353, -0.0599759
Part.ActiveView().RotateAboutCenter -0.0659075, -0.0974608
Part.ActiveView().RotateAboutCenter -0.052726, -0.0599759
Part.ActiveView().RotateAboutCenter -0.0461353, -0.0749698
Part.ActiveView().RotateAboutCenter -0.026363, -0.0674728
Part.ActiveView().RotateAboutCenter -0.0197723, -0.0374849
Part.ActiveView().RotateAboutCenter -0.0131815, -0.0299879
Part.ActiveView().RotateAboutCenter -0.00659075, -0.0224909
Part.ActiveView().RotateAboutCenter -0.00659075, -0.0224909
Part.ActiveView().RotateAboutCenter -0.00659075, -0.0299879
Part.ActiveView().RotateAboutCenter 0.00659075, -0.0449819
Part.ActiveView().RotateAboutCenter 0.00659075, -0.0449819
Part.ActiveView().RotateAboutCenter 0.0131815, -0.0899638
Part.ActiveView().RotateAboutCenter 0.0197723, -0.0899638
Part.ActiveView().RotateAboutCenter 0.0329538, -0.127449
Part.ActiveView().RotateAboutCenter 0.0395445, -0.104958
Part.ActiveView().RotateAboutCenter 0.026363, -0.0599759
Part.ActiveView().RotateAboutCenter 0.0329538, -0.0524789
Part.ActiveView().RotateAboutCenter 0.0197723, -0.0299879
Part.ActiveView().RotateAboutCenter 0.0131815, -0.0224909
Part.ActiveView().RotateAboutCenter 0.026363, -0.0224909
Part.ActiveView().RotateAboutCenter 0.0593168, -0.0524789
Part.ActiveView().RotateAboutCenter 0.0395445, -0.0224909
Part.ActiveView().RotateAboutCenter 0.0922706, -0.0449819
Part.ActiveView().RotateAboutCenter 0.0659075, -0.0224909
Part.ActiveView().RotateAboutCenter 0.131815, -0.00749698
Part.ActiveView().RotateAboutCenter 0.052726, 0
Part.ActiveView().RotateAboutCenter 0.118634, 0
Part.ActiveView().RotateAboutCenter 0.0988613, 0
Part.ActiveView().RotateAboutCenter 0.0461353, 0.014994
Part.ActiveView().RotateAboutCenter 0.0593168, 0.0224909
Part.ActiveView().RotateAboutCenter 0.0922706, 0.0449819
Part.ActiveView().RotateAboutCenter 0.0724983, 0.0449819
Part.ActiveView().RotateAboutCenter 0.0329538, 0.0224909
Part.ActiveView().RotateAboutCenter 0.0329538, 0.0224909
Part.ActiveView().RotateAboutCenter 0.0329538, 0.0224909
Part.ActiveView().RotateAboutCenter 0.0329538, 0.0299879
Part.ActiveView().RotateAboutCenter 0.0659075, 0.0524789
Part.ActiveView().RotateAboutCenter 0.0329538, 0.0449819
Part.ActiveView().RotateAboutCenter 0.0593168, 0.0674728
Part.ActiveView().RotateAboutCenter 0.0131815, 0.0299879
Part.ActiveView().RotateAboutCenter 0.0329538, 0.0524789
Part.ActiveView().RotateAboutCenter 0.0395445, 0.0824668
Part.ActiveView().RotateAboutCenter 0.0197723, 0.0374849
Part.ActiveView().RotateAboutCenter 0.026363, 0.0524789
Part.ActiveView().RotateAboutCenter 0.0197723, 0.0299879
Part.ActiveView().RotateAboutCenter 0.0197723, 0.0449819
Part.ActiveView().RotateAboutCenter 0.0197723, 0.0374849
Part.ActiveView().RotateAboutCenter 0.0197723, 0.0524789
Part.ActiveView().RotateAboutCenter 0.026363, 0.0374849
Part.ActiveView().RotateAboutCenter 0.0197723, 0.0299879
Part.ActiveView().RotateAboutCenter 0.0329538, 0.0524789
Part.ActiveView().RotateAboutCenter 0.0131815, 0.014994
Part.ActiveView().RotateAboutCenter 0.026363, 0.0449819
Part.ActiveView().RotateAboutCenter 0.026363, 0.0374849
Part.ActiveView().RotateAboutCenter 0.0329538, 0.0449819
Part.ActiveView().RotateAboutCenter 0.026363, 0.0299879
Part.ActiveView().RotateAboutCenter 0.0922706, 0.0899638
Part.ActiveView().RotateAboutCenter 0.0197723, 0.0224909
Part.ActiveView().RotateAboutCenter 0.0395445, 0.0374849
Part.ActiveView().RotateAboutCenter 0.052726, 0.0674728
Part.ActiveView().RotateAboutCenter 0.052726, 0.0524789
Part.ActiveView().RotateAboutCenter 0.0724983, 0.0824668
Part.ActiveView().RotateAboutCenter 0.0395445, 0.0374849
Part.ActiveView().RotateAboutCenter 0.0395445, 0.0449819
Part.ActiveView().RotateAboutCenter 0.026363, 0.0374849
Part.ActiveView().RotateAboutCenter 0.0461353, 0.0449819
Part.ActiveView().RotateAboutCenter 0.079089, 0.0599759
Part.ActiveView().RotateAboutCenter 0.079089, 0.0674728
Part.ActiveView().RotateAboutCenter 0.0461353, 0.0374849
Part.ActiveView().RotateAboutCenter 0.0593168, 0.0524789
Part.ActiveView().RotateAboutCenter 0.0461353, 0.0374849
Part.ActiveView().RotateAboutCenter 0.0461353, 0.0299879
Part.ActiveView().RotateAboutCenter 0.0395445, 0.0299879
Part.ActiveView().RotateAboutCenter 0.0395445, 0.0299879
Part.ActiveView().RotateAboutCenter 0.0329538, 0.014994
Part.ActiveView().RotateAboutCenter 0.026363, 0.014994
Part.ActiveView().RotateAboutCenter 0.026363, 0.014994
Part.ActiveView().RotateAboutCenter 0.0329538, 0.014994
Part.ActiveView().RotateAboutCenter 0.0329538, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0395445, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0593168, 0.00749698
Part.ActiveView().RotateAboutCenter 0.026363, 0
Part.ActiveView().RotateAboutCenter 0.0329538, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0395445, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0329538, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0197723, -0.014994
Part.ActiveView().RotateAboutCenter 0.026363, -0.014994
Part.ActiveView().RotateAboutCenter 0.0329538, -0.0599759
Part.ActiveView().RotateAboutCenter 0.0197723, -0.0599759
Part.ActiveView().RotateAboutCenter 0.0329538, -0.0599759
Part.ActiveView().RotateAboutCenter 0.026363, -0.0674728
Part.ActiveView().RotateAboutCenter 0.0329538, -0.0674728
Part.ActiveView().RotateAboutCenter 0.0329538, -0.157437
Part.ActiveView().RotateAboutCenter 0, -0.0899638
Part.ActiveView().RotateAboutCenter 0, -0.127449
Part.ActiveView().RotateAboutCenter 0, -0.0599759
Part.ActiveView().RotateAboutCenter 0, -0.0674728
Part.ActiveView().RotateAboutCenter 0, -0.0224909
Part.ActiveView().RotateAboutCenter 0, -0.0449819
Part.ActiveView().RotateAboutCenter 0, -0.0299879
Part.ActiveView().RotateAboutCenter -0.0131815, -0.014994
Part.ActiveView().RotateAboutCenter -0.0131815, -0.0374849
Part.ActiveView().RotateAboutCenter -0.00659075, -0.0374849
Part.ActiveView().RotateAboutCenter -0.0131815, -0.0449819
Part.ActiveView().RotateAboutCenter -0.0197723, -0.0374849
Part.ActiveView().RotateAboutCenter -0.026363, -0.0749698
Part.ActiveView().RotateAboutCenter -0.0329538, -0.0524789
Part.ActiveView().RotateAboutCenter -0.0329538, -0.0674728
Part.ActiveView().RotateAboutCenter -0.0395445, -0.0599759
Part.ActiveView().RotateAboutCenter -0.0197723, -0.0224909
Part.ActiveView().RotateAboutCenter -0.026363, -0.014994
Part.ActiveView().RotateAboutCenter -0.0395445, -0.0224909
Part.ActiveView().RotateAboutCenter -0.0329538, -0.0224909
Part.ActiveView().RotateAboutCenter -0.0461353, -0.014994
Part.ActiveView().RotateAboutCenter -0.0197723, -0.014994
Part.ActiveView().RotateAboutCenter -0.0197723, 0
boolstatus = Part.Extension.SelectByID("roue_axe-1@Piston sans mobilité", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Part.EditDelete
boolstatus = Part.SetUserPreferenceToggle(5, False)
swApp.ArrangeWindows 1
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 0
Set Part = swApp.ActivateDoc ("Crosse assemblée.SLDASM")
boolstatus = Part.Extension.SelectByID("Crosse assemblée.SLDASM", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Set Part = swApp.ActivateDoc ("Piston sans mobilité.SLDASM")
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
boolstatus = Part.Extension.SelectByID("Crosse assemblée-1@Piston sans mobilité", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("piston_doigt-1@Piston sans mobilité", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Part.RotateComponent
' MSGBOX
' Le composant sélectionné est fixé. Il ne peut pas être déplacé.

Part.SetPickMode
Part.ClearSelection
Part.SetPickMode
boolstatus = Part.Extension.SelectByID("piston_doigt-1@Piston sans mobilité", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("piston_doigt-1@Piston sans mobilité", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Part.UnfixComponent
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("Crosse assemblée-1@Piston sans mobilité", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Crosse assemblée-1@Piston sans mobilité", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Part.FixComponent
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("piston_doigt-1@Piston sans mobilité", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Part.RotateComponent
boolstatus = Part.Extension.SelectByID("", "EDGE", 0.03372132608496, -0.01939065652635, -0.02929103356377, False, 0, Nothing)
' MSGBOX
' Le composant sélectionné est fixé. Il ne peut pas être déplacé.

boolstatus = Part.Extension.SelectByID("", "FACE", -0.00521569406078, 0.01135986511645, 0.01479212417053, False, 0, Nothing)
Part.TranslateComponent
boolstatus = Part.Extension.SelectByID("", "EDGE", -0.0007406972791841, -0.03473804384953, 0.008463479559907, False, 0, Nothing)
' MSGBOX
' Le composant sélectionné est fixé. Il ne peut pas être déplacé.

boolstatus = Part.Extension.SelectByID("", "FACE", -0.03979222681676, 0.001578812709113, 0.06503835154854, False, 0, Nothing)
Part.ClearSelection
Part.ViewZoomtofit2
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter -0.0197723, -0.0224909
Part.ActiveView().RotateAboutCenter -0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter -0.0395445, -0.0299879
Part.ActiveView().RotateAboutCenter -0.0131815, -0.014994
Part.ActiveView().RotateAboutCenter -0.0197723, -0.0224909
Part.ActiveView().RotateAboutCenter -0.0395445, -0.0299879
Part.ActiveView().RotateAboutCenter -0.0197723, -0.0224909
Part.ActiveView().RotateAboutCenter -0.0395445, -0.0299879
Part.ActiveView().RotateAboutCenter -0.026363, -0.0224909
Part.ActiveView().RotateAboutCenter -0.0197723, -0.0224909
Part.ActiveView().RotateAboutCenter -0.0197723, -0.00749698
Part.ActiveView().RotateAboutCenter -0.0197723, -0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter -0.0197723, -0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter -0.0329538, -0.014994
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.026363, -0.00749698
Part.ActiveView().RotateAboutCenter -0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter -0.0329538, -0.00749698
Part.ActiveView().RotateAboutCenter -0.0395445, -0.00749698
Part.ActiveView().RotateAboutCenter -0.0329538, -0.014994
Part.ActiveView().RotateAboutCenter -0.0197723, -0.00749698
Part.ActiveView().RotateAboutCenter -0.0593168, 0
Part.ActiveView().RotateAboutCenter -0.026363, -0.00749698
Part.ActiveView().RotateAboutCenter -0.0461353, 0
Part.ActiveView().RotateAboutCenter -0.0329538, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0197723, 0
Part.ActiveView().RotateAboutCenter -0.0395445, 0.014994
Part.ActiveView().RotateAboutCenter -0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0197723, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0461353, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0197723, 0
Part.ActiveView().RotateAboutCenter -0.0131815, 0
Part.ActiveView().RotateAboutCenter -0.052726, 0.0224909
Part.ActiveView().RotateAboutCenter -0.0131815, 0
Part.ActiveView().RotateAboutCenter -0.0197723, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
boolstatus = Part.Extension.SelectByID("Contraintes", "MATEGROUPS", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "FACE", -0.04915205311028, -0.02867594617501, -0.01248171049065, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "FACE", -0.1031958316999, -0.03587406429281, -0.0159434352899, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "FACE", -0.05803030756783, -0.03154809940145, -0.01198586628664, True, 0, Nothing)
Part.AddMate 1, 2, False, 0.02229120372054, 0.5235987755983
Part.ClearSelection
Part.SetPickMode
Part.SetPickMode
Part.SetPickMode
Part.SetPickMode
Part.SetPickMode
Part.SetPickMode
Part.SetPickMode
Part.SetPickMode
Part.SetPickMode
Part.SetPickMode
Part.SetPickMode
Part.SetPickMode
Part.SetPickMode
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, -0.0224909
Part.ActiveView().RotateAboutCenter -0.00659075, -0.0224909
Part.ActiveView().RotateAboutCenter 0, -0.0299879
Part.ActiveView().RotateAboutCenter -0.00659075, -0.0299879
Part.ActiveView().RotateAboutCenter 0, -0.0299879
Part.ActiveView().RotateAboutCenter -0.0131815, -0.0299879
Part.ActiveView().RotateAboutCenter 0, -0.014994
Part.ActiveView().RotateAboutCenter 0, -0.0299879
Part.ActiveView().RotateAboutCenter 0, -0.014994
Part.ActiveView().RotateAboutCenter 0, -0.0374849
Part.ActiveView().RotateAboutCenter 0, -0.0299879
Part.ActiveView().RotateAboutCenter 0, -0.0374849
Part.ActiveView().RotateAboutCenter 0, -0.0299879
Part.ActiveView().RotateAboutCenter -0.00659075, -0.0224909
Part.ActiveView().RotateAboutCenter 0, -0.014994
Part.ActiveView().RotateAboutCenter -0.00659075, -0.014994
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter 0, -0.0449819
Part.ActiveView().RotateAboutCenter -0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, -0.0599759
Part.ActiveView().RotateAboutCenter 0, -0.0224909
Part.ActiveView().RotateAboutCenter -0.0197723, -0.0674728
Part.ActiveView().RotateAboutCenter -0.0131815, -0.0374849
Part.ActiveView().RotateAboutCenter 0, -0.0374849
Part.ActiveView().RotateAboutCenter -0.0197723, -0.0299879
Part.ActiveView().RotateAboutCenter -0.00659075, -0.0374849
Part.ActiveView().RotateAboutCenter -0.00659075, -0.014994
Part.ActiveView().RotateAboutCenter -0.0197723, -0.0374849
Part.ActiveView().RotateAboutCenter 0, -0.014994
Part.ActiveView().RotateAboutCenter -0.0131815, -0.0299879
Part.ActiveView().RotateAboutCenter 0, -0.014994
Part.ActiveView().RotateAboutCenter -0.0131815, -0.0299879
Part.ActiveView().RotateAboutCenter 0, -0.0224909
Part.ActiveView().RotateAboutCenter -0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter 0, -0.014994
Part.ViewZoomTo2 -0.107844, -0.000249588, -0.00274749, -0.0832971, -0.033306, -0.00274749
boolstatus = Part.Extension.SelectByID("", "FACE", -0.08104145624827, -0.03926542804544, -0.002616377072854, False, 0, Nothing)
Part.ViewZoomtofit2
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0197723, 0.0224909
Part.ActiveView().RotateAboutCenter 0.0197723, 0.0224909
Part.ActiveView().RotateAboutCenter 0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter 0.0461353, 0.0524789
Part.ActiveView().RotateAboutCenter 0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter 0.0131815, 0.0299879
Part.ActiveView().RotateAboutCenter 0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, 0.0224909
Part.ActiveView().RotateAboutCenter 0.00659075, 0.0224909
Part.ActiveView().RotateAboutCenter 0.00659075, 0.0224909
Part.ActiveView().RotateAboutCenter 0.0131815, 0.0224909
Part.ActiveView().RotateAboutCenter 0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter 0.00659075, 0.0299879
Part.ActiveView().RotateAboutCenter 0.00659075, 0.0224909
Part.ActiveView().RotateAboutCenter 0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter 0, 0.014994
Part.ActiveView().RotateAboutCenter 0.0197723, 0.0374849
Part.ActiveView().RotateAboutCenter 0, 0.014994
Part.ActiveView().RotateAboutCenter 0.0131815, 0.0374849
Part.ActiveView().RotateAboutCenter 0.00659075, 0.0299879
Part.ActiveView().RotateAboutCenter 0.00659075, 0.0299879
Part.ActiveView().RotateAboutCenter 0.0131815, 0.0224909
Part.ActiveView().RotateAboutCenter 0.00659075, 0.0224909
Part.ActiveView().RotateAboutCenter 0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter 0.00659075, 0.0224909
Part.ActiveView().RotateAboutCenter 0, 0.0224909
Part.ActiveView().RotateAboutCenter 0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter 0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter 0.0131815, 0.014994
Part.ActiveView().RotateAboutCenter 0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, 0.014994
Part.ActiveView().RotateAboutCenter 0.0197723, 0.0224909
Part.ActiveView().RotateAboutCenter 0.026363, 0.0224909
Part.ActiveView().RotateAboutCenter 0.026363, 0.014994
Part.ActiveView().RotateAboutCenter 0.0197723, 0.0224909
Part.ActiveView().RotateAboutCenter 0.026363, 0.0224909
Part.ActiveView().RotateAboutCenter 0.026363, 0.0374849
Part.ActiveView().RotateAboutCenter 0.0197723, 0.0224909
Part.ActiveView().RotateAboutCenter 0.0197723, 0.0374849
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, 0.0299879
Part.ActiveView().RotateAboutCenter 0.0131815, 0
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ActiveView().RotateAboutCenter 0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, 0
Part.ActiveView().RotateAboutCenter 0.0131815, 0.014994
Part.ActiveView().RotateAboutCenter 0.0197723, 0
Part.ActiveView().RotateAboutCenter 0.0131815, 0.014994
Part.ActiveView().RotateAboutCenter 0.026363, 0
Part.ActiveView().RotateAboutCenter 0.0131815, 0.014994
Part.ActiveView().RotateAboutCenter 0.0131815, 0
Part.ActiveView().RotateAboutCenter 0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, 0
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ActiveView().RotateAboutCenter 0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ActiveView().RotateAboutCenter 0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ActiveView().RotateAboutCenter 0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ViewZoomTo2 -0.0598381, 0.00131402, -0.00244282, -0.0107255, -0.0370255, -0.00244282
Part.ActiveView().RotateAboutCenter 0, 0.0224909
Part.ActiveView().RotateAboutCenter -0.0131815, 0.014994
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0131815, 0.0224909
Part.ActiveView().RotateAboutCenter -0.00659075, 0.0374849
Part.ActiveView().RotateAboutCenter -0.0197723, 0.0374849
Part.ActiveView().RotateAboutCenter -0.026363, 0.0524789
Part.ActiveView().RotateAboutCenter -0.0197723, 0.0524789
Part.ActiveView().RotateAboutCenter -0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter -0.026363, 0.0449819
Part.ActiveView().RotateAboutCenter -0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter -0.0197723, 0.0374849
Part.ActiveView().RotateAboutCenter -0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter -0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter -0.00659075, 0.0224909
Part.ActiveView().RotateAboutCenter -0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0131815, 0.014994
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter 0, 0.014994
Part.ActiveView().RotateAboutCenter -0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter 0, -0.0449819
Part.ActiveView().RotateAboutCenter 0.00659075, -0.0374849
Part.ActiveView().RotateAboutCenter 0.0131815, -0.0374849
Part.ActiveView().RotateAboutCenter 0.0131815, -0.0599759
Part.ActiveView().RotateAboutCenter 0.0131815, -0.0449819
Part.ActiveView().RotateAboutCenter 0.0131815, -0.0449819
Part.ActiveView().RotateAboutCenter 0.00659075, -0.0299879
Part.ActiveView().RotateAboutCenter 0.00659075, -0.0299879
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, -0.014994
Part.ActiveView().RotateAboutCenter 0, -0.014994
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ActiveView().RotateAboutCenter 0.0131815, -0.014994
Part.ActiveView().RotateAboutCenter 0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, -0.014994
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ActiveView().RotateAboutCenter 0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.0197723, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0197723, 0.014994
Part.ActiveView().RotateAboutCenter -0.026363, 0.00749698
Part.ActiveView().RotateAboutCenter -0.026363, 0
Part.ActiveView().RotateAboutCenter -0.0197723, 0
Part.ActiveView().RotateAboutCenter -0.0197723, 0
Part.ActiveView().RotateAboutCenter -0.026363, 0
Part.ActiveView().RotateAboutCenter -0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter -0.0131815, 0
Part.ActiveView().RotateAboutCenter -0.0131815, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.0131815, 0
Part.ActiveView().RotateAboutCenter -0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.0131815, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.0131815, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter -0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter -0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0131815, 0
Part.ActiveView().RotateAboutCenter -0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.0131815, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.0131815, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter -0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter -0.0131815, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.0131815, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.0131815, 0
Part.ActiveView().RotateAboutCenter -0.0197723, 0
Part.ActiveView().RotateAboutCenter -0.0131815, 0
Part.ActiveView().RotateAboutCenter -0.0131815, 0.014994
Part.ActiveView().RotateAboutCenter -0.0131815, 0
Part.ActiveView().RotateAboutCenter -0.0197723, 0.014994
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0197723, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter -0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0131815, 0.014994
Part.ActiveView().RotateAboutCenter -0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter -0.0197723, 0.014994
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter -0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter 0, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, 0.014994
Part.ActiveView().RotateAboutCenter 0.0131815, 0.014994
Part.ActiveView().RotateAboutCenter 0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ActiveView().RotateAboutCenter 0.0131815, 0
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ActiveView().RotateAboutCenter 0.0197723, -0.014994
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ActiveView().RotateAboutCenter 0.00659075, -0.00749698
boolstatus = Part.Extension.SelectByID("", "EDGE", -0.0129397521406, -0.007550058476852, -0.004564884374247, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "FACE", -0.02399999999983, -0.01699124443553, 0.001604805312184, True, 0, Nothing)
Part.DeSelectByID "", "EDGE", -0.0129397521406, -0.007550058476852, -0.004564884374247
Part.AddMate 0, 2, False, 0.05704145624817, 0
Part.ClearSelection
Part.ViewZoomtofit2
Part.ActiveView().RotateAboutCenter 0, -0.0224909
Part.ActiveView().RotateAboutCenter 0, -0.014994
Part.ActiveView().RotateAboutCenter 0.00659075, -0.0449819
Part.ActiveView().RotateAboutCenter 0.00659075, -0.0299879
Part.ActiveView().RotateAboutCenter 0, -0.0974608
Part.ActiveView().RotateAboutCenter 0, -0.0224909
Part.ActiveView().RotateAboutCenter 0, -0.0449819
Part.ActiveView().RotateAboutCenter 0, -0.0299879
Part.ActiveView().RotateAboutCenter 0, -0.0299879
Part.ActiveView().RotateAboutCenter -0.00659075, -0.0299879
Part.ActiveView().RotateAboutCenter 0, -0.0374849
Part.ActiveView().RotateAboutCenter 0, -0.014994
Part.ActiveView().RotateAboutCenter 0, -0.0599759
Part.ActiveView().RotateAboutCenter 0, -0.0374849
Part.ActiveView().RotateAboutCenter 0, -0.0374849
Part.ActiveView().RotateAboutCenter 0, -0.0374849
Part.ActiveView().RotateAboutCenter 0, -0.0224909
Part.ActiveView().RotateAboutCenter 0, -0.0224909
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, -0.014994
Part.ActiveView().RotateAboutCenter 0, -0.014994
Part.ActiveView().RotateAboutCenter 0.00659075, -0.014994
Part.ActiveView().RotateAboutCenter 0.0197723, -0.0524789
Part.ActiveView().RotateAboutCenter 0.00659075, -0.014994
Part.ActiveView().RotateAboutCenter 0.0131815, -0.0299879
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, -0.0299879
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, -0.0224909
Part.ActiveView().RotateAboutCenter 0.00659075, -0.014994
Part.ActiveView().RotateAboutCenter 0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0197723, -0.0374849
Part.ActiveView().RotateAboutCenter 0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0197723, -0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0329538, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0329538, -0.014994
Part.ActiveView().RotateAboutCenter 0.0197723, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0197723, 0
Part.ActiveView().RotateAboutCenter 0.0131815, 0
Part.ActiveView().RotateAboutCenter 0.0659075, 0
Part.ActiveView().RotateAboutCenter 0.026363, 0
Part.ActiveView().RotateAboutCenter 0.0724983, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0197723, 0
Part.ActiveView().RotateAboutCenter 0.052726, 0
Part.ActiveView().RotateAboutCenter 0.0197723, 0
Part.ActiveView().RotateAboutCenter 0.0131815, 0
Part.ActiveView().RotateAboutCenter 0.026363, 0
Part.ActiveView().RotateAboutCenter 0.0197723, 0
Part.ActiveView().RotateAboutCenter 0.0131815, 0
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ActiveView().RotateAboutCenter 0.0131815, 0
Part.ActiveView().RotateAboutCenter 0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0197723, 0
Part.ActiveView().RotateAboutCenter 0.0131815, 0
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.0461353, 0.0299879
Part.ActiveView().RotateAboutCenter -0.0988613, 0.0599759
Part.ActiveView().RotateAboutCenter -0.0395445, 0.0224909
Part.ActiveView().RotateAboutCenter -0.052726, 0.0224909
Part.ActiveView().RotateAboutCenter -0.0197723, 0.00749698
Part.ActiveView().RotateAboutCenter -0.026363, 0.00749698
Part.ActiveView().RotateAboutCenter -0.026363, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0197723, 0.00749698
Part.ActiveView().RotateAboutCenter -0.026363, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0395445, 0.0224909
Part.ActiveView().RotateAboutCenter -0.0988613, 0.0449819
Part.ActiveView().RotateAboutCenter -0.0197723, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0461353, 0.0224909
Part.ActiveView().RotateAboutCenter -0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0197723, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0395445, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0329538, 0.014994
Part.ActiveView().RotateAboutCenter -0.0395445, 0.014994
Part.ActiveView().RotateAboutCenter -0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0197723, 0.00749698
Part.ActiveView().RotateAboutCenter -0.026363, 0.014994
Part.ActiveView().RotateAboutCenter -0.0329538, 0.0224909
Part.ActiveView().RotateAboutCenter -0.0329538, 0.014994
Part.ActiveView().RotateAboutCenter -0.0329538, 0.0224909
Part.ActiveView().RotateAboutCenter -0.026363, 0.0224909
Part.ActiveView().RotateAboutCenter -0.026363, 0.014994
Part.ActiveView().RotateAboutCenter -0.052726, 0.0449819
Part.ActiveView().RotateAboutCenter -0.0131815, 0
Part.ActiveView().RotateAboutCenter -0.0197723, 0.014994
Part.ActiveView().RotateAboutCenter -0.026363, 0.0224909
Part.ActiveView().RotateAboutCenter -0.026363, 0.014994
Part.ActiveView().RotateAboutCenter -0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0197723, 0.014994
Part.ActiveView().RotateAboutCenter -0.026363, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0197723, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0197723, 0.014994
Part.ActiveView().RotateAboutCenter -0.0329538, 0.014994
Part.ActiveView().RotateAboutCenter -0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter -0.026363, 0.014994
Part.ActiveView().RotateAboutCenter -0.0197723, 0.014994
Part.ActiveView().RotateAboutCenter -0.0197723, 0.014994
Part.ActiveView().RotateAboutCenter -0.0329538, 0.014994
Part.ActiveView().RotateAboutCenter -0.0329538, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0329538, 0.0224909
Part.ActiveView().RotateAboutCenter -0.0329538, 0.014994
Part.ActiveView().RotateAboutCenter -0.0197723, 0.014994
Part.ActiveView().RotateAboutCenter -0.0593168, 0.0224909
Part.ActiveView().RotateAboutCenter -0.026363, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0197723, 0.014994
Part.ActiveView().RotateAboutCenter -0.0197723, 0
Part.ActiveView().RotateAboutCenter -0.0197723, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0.00749698
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter -0.0329538, 0.014994
Part.ActiveView().RotateAboutCenter -0.0131815, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0197723, 0.014994
Part.ActiveView().RotateAboutCenter -0.0329538, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0197723, 0.00749698
Part.ActiveView().RotateAboutCenter -0.026363, 0.014994
Part.ActiveView().RotateAboutCenter -0.0131815, 0
Part.ActiveView().RotateAboutCenter -0.00659075, 0
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ActiveView().RotateAboutCenter 0.026363, 0
Part.ActiveView().RotateAboutCenter 0.0329538, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0395445, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0395445, -0.00749698
Part.ActiveView().RotateAboutCenter 0.026363, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0197723, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0461353, 0
Part.ActiveView().RotateAboutCenter 0.0131815, 0
Part.ActiveView().RotateAboutCenter 0.0461353, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0197723, 0
Part.ActiveView().RotateAboutCenter 0.0329538, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0329538, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0395445, 0
Part.ActiveView().RotateAboutCenter 0.0329538, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, 0
Part.ActiveView().RotateAboutCenter 0.0461353, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0197723, 0
Part.ActiveView().RotateAboutCenter 0.0724983, -0.014994
Part.ActiveView().RotateAboutCenter 0.026363, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0593168, -0.0224909
Part.ActiveView().RotateAboutCenter 0.0131815, 0
Part.ActiveView().RotateAboutCenter 0.0329538, -0.014994
Part.ActiveView().RotateAboutCenter 0.0395445, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0329538, -0.0224909
Part.ActiveView().RotateAboutCenter 0.0329538, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0329538, -0.014994
Part.ActiveView().RotateAboutCenter 0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0329538, -0.0224909
Part.ActiveView().RotateAboutCenter 0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter 0.026363, -0.014994
Part.ActiveView().RotateAboutCenter 0.0131815, 0
Part.ActiveView().RotateAboutCenter 0.0197723, -0.014994
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ActiveView().RotateAboutCenter 0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0197723, -0.00749698
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0197723, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, 0
Part.ActiveView().RotateAboutCenter 0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0197723, 0
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ActiveView().RotateAboutCenter 0.0197723, -0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ActiveView().RotateAboutCenter 0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, 0
Part.ActiveView().RotateAboutCenter 0.0131815, 0
Part.ActiveView().RotateAboutCenter 0.0197723, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, 0
Part.ActiveView().RotateAboutCenter 0.0197723, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0197723, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, 0
Part.ActiveView().RotateAboutCenter 0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, 0
Part.ActiveView().RotateAboutCenter 0.0197723, -0.014994
Part.ActiveView().RotateAboutCenter 0.0329538, -0.00749698
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter 0.026363, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter 0.026363, -0.014994
Part.ActiveView().RotateAboutCenter 0.0197723, -0.00749698
Part.ActiveView().RotateAboutCenter 0.026363, -0.014994
Part.ActiveView().RotateAboutCenter 0.0197723, -0.014994
Part.ActiveView().RotateAboutCenter 0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, -0.00749698
Part.ActiveView().RotateAboutCenter 0.00659075, 0
boolstatus = Part.Extension.SelectByID("", "EDGE", -0.03609788638953, -0.03661626272928, 0.008402939911434, False, 0, Nothing)
Part.ViewZoomTo2 -0.0862314, -0.0184209, -0.0182074, -0.0596863, -0.0387808, -0.0182074
boolstatus = Part.Extension.SelectByID("", "EDGE", -0.04920053920667, -0.04048514948109, 2.643801849445e-006, True, 0, Nothing)
Part.AddMate 0, 2, False, 0.008838673359771, 0
Part.ClearSelection
Part.ViewZoomtofit2
' MSGBOX
' Certains des modèles référencés dans ce document ont été modifiés. Ils doivent être enregistrés lorsque le document est enregistré.
' 		Enregistrer le document et les modèles référencés maintenant ?

Part.Save2 FALSE
Part.SetPickMode
swApp.LoadFile2 "C:\Program Files\SolidWorks EE 2002-2003\data\templates\Assemblage.asmdot", ""
Set Part = swApp.ActiveDoc
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
Set Part = swApp.NewDocument ("C:\Program Files\SolidWorks EE 2002-2003\data\templates\Assemblage.asmdot", 0, 0.000000, 0.000000)
Set Part = swApp.ActivateDoc ("Assem2")
Part.SaveAs2 "E:\TP Labo MPSI\Supports\Doshydro\Maquette numérique\Pompe a assembler 1.SLDASM", 0, FALSE, FALSE
swApp.ArrangeWindows 1
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 0
swApp.ActiveDoc.ActiveView.FrameWidth = 609
swApp.ActiveDoc.ActiveView.FrameHeight = 298
Set Part = swApp.ActivateDoc ("piston_doigt.SLDASM")
Part.ClearSelection
Set Part = Nothing
swApp.CloseDoc "piston_doigt.SLDASM"
Set Part = swApp.ActivateDoc ("Pompe a assembler 1.SLDASM")
Set Part = swApp.ActivateDoc ("Crosse assemblée.SLDASM")
Part.ClearSelection
Set Part = Nothing
swApp.CloseDoc "Crosse assemblée.SLDASM"
Set Part = swApp.ActivateDoc ("Pompe a assembler 1.SLDASM")
Set Part = swApp.ActivateDoc ("roue_axe.SLDASM")
boolstatus = Part.Extension.SelectByID("roue_axe.SLDASM", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Set Part = swApp.ActivateDoc ("Pompe a assembler 1.SLDASM")
Set Part = swApp.ActivateDoc ("Piston sans mobilité.SLDASM")
boolstatus = Part.Extension.SelectByID("Piston sans mobilité.SLDASM", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Set Part = swApp.ActivateDoc ("Pompe a assembler 1.SLDASM")
Set Part = swApp.ActivateDoc ("noix.SLDPRT")
boolstatus = Part.Extension.SelectByID("noix.SLDPRT", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Set Part = swApp.ActivateDoc ("Pompe a assembler 1.SLDASM")
Set Part = swApp.ActivateDoc ("Carter_assemblé.SLDASM")
swApp.ActiveDoc.ActiveView.FrameLeft = 609
swApp.ActiveDoc.ActiveView.FrameTop = 666
swApp.ActiveDoc.ActiveView.FrameLeft = 608
swApp.ActiveDoc.ActiveView.FrameTop = 663
swApp.ActiveDoc.ActiveView.FrameLeft = 607
swApp.ActiveDoc.ActiveView.FrameTop = 660
swApp.ActiveDoc.ActiveView.FrameLeft = 604
swApp.ActiveDoc.ActiveView.FrameTop = 652
swApp.ActiveDoc.ActiveView.FrameLeft = 602
swApp.ActiveDoc.ActiveView.FrameTop = 642
swApp.ActiveDoc.ActiveView.FrameLeft = 600
swApp.ActiveDoc.ActiveView.FrameTop = 635
swApp.ActiveDoc.ActiveView.FrameLeft = 598
swApp.ActiveDoc.ActiveView.FrameTop = 627
swApp.ActiveDoc.ActiveView.FrameLeft = 597
swApp.ActiveDoc.ActiveView.FrameTop = 619
swApp.ActiveDoc.ActiveView.FrameLeft = 597
swApp.ActiveDoc.ActiveView.FrameTop = 611
swApp.ActiveDoc.ActiveView.FrameLeft = 596
swApp.ActiveDoc.ActiveView.FrameTop = 600
swApp.ActiveDoc.ActiveView.FrameLeft = 595
swApp.ActiveDoc.ActiveView.FrameTop = 589
swApp.ActiveDoc.ActiveView.FrameLeft = 594
swApp.ActiveDoc.ActiveView.FrameTop = 576
swApp.ActiveDoc.ActiveView.FrameLeft = 593
swApp.ActiveDoc.ActiveView.FrameTop = 563
swApp.ActiveDoc.ActiveView.FrameLeft = 591
swApp.ActiveDoc.ActiveView.FrameTop = 538
swApp.ActiveDoc.ActiveView.FrameLeft = 590
swApp.ActiveDoc.ActiveView.FrameTop = 508
swApp.ActiveDoc.ActiveView.FrameLeft = 588
swApp.ActiveDoc.ActiveView.FrameTop = 491
swApp.ActiveDoc.ActiveView.FrameLeft = 588
swApp.ActiveDoc.ActiveView.FrameTop = 471
swApp.ActiveDoc.ActiveView.FrameLeft = 587
swApp.ActiveDoc.ActiveView.FrameTop = 454
swApp.ActiveDoc.ActiveView.FrameLeft = 586
swApp.ActiveDoc.ActiveView.FrameTop = 434
swApp.ActiveDoc.ActiveView.FrameLeft = 585
swApp.ActiveDoc.ActiveView.FrameTop = 417
swApp.ActiveDoc.ActiveView.FrameLeft = 583
swApp.ActiveDoc.ActiveView.FrameTop = 397
swApp.ActiveDoc.ActiveView.FrameLeft = 582
swApp.ActiveDoc.ActiveView.FrameTop = 377
swApp.ActiveDoc.ActiveView.FrameLeft = 579
swApp.ActiveDoc.ActiveView.FrameTop = 338
swApp.ActiveDoc.ActiveView.FrameLeft = 579
swApp.ActiveDoc.ActiveView.FrameTop = 280
swApp.ActiveDoc.ActiveView.FrameLeft = 579
swApp.ActiveDoc.ActiveView.FrameTop = 207
swApp.ActiveDoc.ActiveView.FrameLeft = 581
swApp.ActiveDoc.ActiveView.FrameTop = 168
swApp.ActiveDoc.ActiveView.FrameLeft = 579
swApp.ActiveDoc.ActiveView.FrameTop = 93
swApp.ActiveDoc.ActiveView.FrameLeft = 579
swApp.ActiveDoc.ActiveView.FrameTop = 64
swApp.ActiveDoc.ActiveView.FrameLeft = 579
swApp.ActiveDoc.ActiveView.FrameTop = 52
swApp.ActiveDoc.ActiveView.FrameLeft = 579
swApp.ActiveDoc.ActiveView.FrameTop = 40
swApp.ActiveDoc.ActiveView.FrameLeft = 579
swApp.ActiveDoc.ActiveView.FrameTop = 28
swApp.ActiveDoc.ActiveView.FrameLeft = 580
swApp.ActiveDoc.ActiveView.FrameTop = 16
swApp.ActiveDoc.ActiveView.FrameLeft = 580
swApp.ActiveDoc.ActiveView.FrameTop = 3
swApp.ActiveDoc.ActiveView.FrameLeft = 579
swApp.ActiveDoc.ActiveView.FrameTop = -16
swApp.ActiveDoc.ActiveView.FrameLeft = 576
swApp.ActiveDoc.ActiveView.FrameTop = -21
swApp.ActiveDoc.ActiveView.FrameLeft = 575
swApp.ActiveDoc.ActiveView.FrameTop = -21
swApp.ActiveDoc.ActiveView.FrameWidth = 609
swApp.ActiveDoc.ActiveView.FrameHeight = 225
swApp.ActiveDoc.ActiveView.FrameWidth = 609
swApp.ActiveDoc.ActiveView.FrameHeight = 248
swApp.ActiveDoc.ActiveView.FrameWidth = 609
swApp.ActiveDoc.ActiveView.FrameHeight = 303
swApp.ActiveDoc.ActiveView.FrameWidth = 609
swApp.ActiveDoc.ActiveView.FrameHeight = 360
swApp.ActiveDoc.ActiveView.FrameWidth = 609
swApp.ActiveDoc.ActiveView.FrameHeight = 467
swApp.ActiveDoc.ActiveView.FrameWidth = 609
swApp.ActiveDoc.ActiveView.FrameHeight = 551
swApp.ActiveDoc.ActiveView.FrameWidth = 609
swApp.ActiveDoc.ActiveView.FrameHeight = 631
swApp.ActiveDoc.ActiveView.FrameWidth = 609
swApp.ActiveDoc.ActiveView.FrameHeight = 720
swApp.ActiveDoc.ActiveView.FrameWidth = 609
swApp.ActiveDoc.ActiveView.FrameHeight = 766
swApp.ActiveDoc.ActiveView.FrameWidth = 609
swApp.ActiveDoc.ActiveView.FrameHeight = 782
boolstatus = Part.Extension.SelectByID("Carter_assemblé.SLDASM", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Carter_assemblé.SLDASM", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Set Part = swApp.ActivateDoc ("Pompe a assembler 1.SLDASM")
Set Part = swApp.ActivateDoc ("Carter_assemblé.SLDASM")
swApp.ActiveDoc.ActiveView.FrameLeft = 568
swApp.ActiveDoc.ActiveView.FrameTop = -16
swApp.ActiveDoc.ActiveView.FrameLeft = 561
swApp.ActiveDoc.ActiveView.FrameTop = -6
swApp.ActiveDoc.ActiveView.FrameLeft = 549
swApp.ActiveDoc.ActiveView.FrameTop = 16
swApp.ActiveDoc.ActiveView.FrameLeft = 541
swApp.ActiveDoc.ActiveView.FrameTop = 37
swApp.ActiveDoc.ActiveView.FrameLeft = 527
swApp.ActiveDoc.ActiveView.FrameTop = 93
swApp.ActiveDoc.ActiveView.FrameLeft = 515
swApp.ActiveDoc.ActiveView.FrameTop = 124
swApp.ActiveDoc.ActiveView.FrameLeft = 511
swApp.ActiveDoc.ActiveView.FrameTop = 137
Set Part = swApp.ActivateDoc ("Pompe a assembler 1.SLDASM")
' MSGBOX
' Certains des modèles référencés dans ce document ont été modifiés. Ils doivent être enregistrés lorsque le document est enregistré.
' 		Enregistrer le document et les modèles référencés maintenant ?

Part.Save2 FALSE
Set Part = swApp.ActivateDoc ("Carter_assemblé.SLDASM")
Part.ClearSelection
Set Part = Nothing
swApp.CloseDoc "Carter_assemblé.SLDASM"
Set Part = swApp.ActivateDoc ("Pompe a assembler 1.SLDASM")
Set Part = swApp.ActivateDoc ("roue_axe.SLDASM")
Part.ClearSelection
Set Part = Nothing
swApp.CloseDoc "roue_axe.SLDASM"
Set Part = swApp.ActivateDoc ("Pompe a assembler 1.SLDASM")
Set Part = swApp.ActivateDoc ("noix.SLDPRT")
Part.ClearSelection
Set Part = Nothing
swApp.CloseDoc "noix.SLDPRT"
Set Part = swApp.ActivateDoc ("Pompe a assembler 1.SLDASM")
Set Part = swApp.ActivateDoc ("Piston sans mobilité.SLDASM")
Part.ClearSelection
Set Part = Nothing
swApp.CloseDoc "Piston sans mobilité.SLDASM"
Set Part = swApp.ActivateDoc ("Pompe a assembler 1.SLDASM")
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
Part.ViewZoomtofit2
Part.ActiveView().RotateAboutCenter 0.0131815, -0.00749698
Part.ActiveView().RotateAboutCenter 0.026363, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0724983, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0593168, -0.014994
Part.ActiveView().RotateAboutCenter 0.0329538, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0461353, -0.00749698
Part.ActiveView().RotateAboutCenter 0.052726, 0
Part.ActiveView().RotateAboutCenter 0.0395445, -0.0224909
Part.ActiveView().RotateAboutCenter 0.0329538, -0.014994
Part.ActiveView().RotateAboutCenter 0.0329538, -0.0224909
Part.ActiveView().RotateAboutCenter 0.0329538, -0.014994
Part.ActiveView().RotateAboutCenter 0.0329538, -0.0224909
Part.ActiveView().RotateAboutCenter 0.0131815, -0.014994
Part.ActiveView().RotateAboutCenter 0.0329538, -0.0374849
Part.ActiveView().RotateAboutCenter 0.0131815, -0.014994
Part.ActiveView().RotateAboutCenter 0.026363, -0.0374849
Part.ActiveView().RotateAboutCenter 0.0197723, -0.0374849
Part.ActiveView().RotateAboutCenter 0.026363, -0.0374849
Part.ActiveView().RotateAboutCenter 0.0329538, -0.0374849
Part.ActiveView().RotateAboutCenter 0.026363, -0.0374849
Part.ActiveView().RotateAboutCenter 0.0197723, -0.0524789
Part.ActiveView().RotateAboutCenter 0.0197723, -0.0224909
Part.ActiveView().RotateAboutCenter 0.0131815, -0.0524789
Part.ActiveView().RotateAboutCenter 0.0131815, -0.0374849
Part.ActiveView().RotateAboutCenter 0.00659075, -0.0224909
Part.ActiveView().RotateAboutCenter 0, -0.0299879
Part.ActiveView().RotateAboutCenter 0, -0.0299879
Part.ActiveView().RotateAboutCenter 0, -0.0224909
Part.ActiveView().RotateAboutCenter 0, -0.014994
Part.ActiveView().RotateAboutCenter 0, -0.00749698
Part.ActiveView().RotateAboutCenter 0.0131815, 0
Part.ActiveView().RotateAboutCenter 0.0395445, 0.00749698
Part.ActiveView().RotateAboutCenter 0.0461353, 0.0374849
Part.ActiveView().RotateAboutCenter 0.026363, 0.0224909
Part.ActiveView().RotateAboutCenter 0.0329538, 0.0599759
Part.ActiveView().RotateAboutCenter 0.0461353, 0.0974608
Part.ActiveView().RotateAboutCenter 0.0329538, 0.0749698
Part.ActiveView().RotateAboutCenter 0.0395445, 0.0749698
Part.ActiveView().RotateAboutCenter 0.0329538, 0.0974608
Part.ActiveView().RotateAboutCenter 0.0131815, 0.0974608
Part.ActiveView().RotateAboutCenter 0, 0.0599759
Part.ActiveView().RotateAboutCenter -0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter -0.00659075, 0.014994
Part.ActiveView().RotateAboutCenter -0.0395445, 0.0224909
Part.ActiveView().RotateAboutCenter -0.026363, 0.014994
Part.ActiveView().RotateAboutCenter -0.0329538, 0.00749698
Part.ActiveView().RotateAboutCenter -0.0461353, 0
Part.ActiveView().RotateAboutCenter -0.0461353, -0.00749698
Part.ActiveView().RotateAboutCenter -0.026363, -0.00749698
Part.ActiveView().RotateAboutCenter -0.079089, -0.0524789
Part.ActiveView().RotateAboutCenter -0.0461353, -0.0374849
Part.ActiveView().RotateAboutCenter -0.0395445, -0.0374849
Part.ActiveView().RotateAboutCenter -0.0461353, -0.0749698
Part.ActiveView().RotateAboutCenter -0.0856798, -0.142443
Part.ActiveView().RotateAboutCenter -0.026363, -0.0599759
Part.ActiveView().RotateAboutCenter -0.0659075, -0.127449
Part.ActiveView().RotateAboutCenter -0.052726, -0.104958
Part.ActiveView().RotateAboutCenter -0.0131815, -0.0224909
Part.ActiveView().RotateAboutCenter 0, -0.00749698
boolstatus = Part.SetUserPreferenceToggle(5, False)
Part.Save2 FALSE
boolstatus = Part.Extension.SelectByID("roue_axe-1@Pompe a assembler 1", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Carter_assemblé-1@Pompe a assembler 1", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Carter_assemblé-1@Pompe a assembler 1", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Part.FixComponent
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("roue_axe-1@Pompe a assembler 1", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("roue_axe-1@Pompe a assembler 1", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Part.UnfixComponent
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("Piston sans mobilité-1@Pompe a assembler 1", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Piston sans mobilité-1@Pompe a assembler 1", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("noix-1@Pompe a assembler 1", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("noix-1@Pompe a assembler 1", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Carter_assemblé-1@Pompe a assembler 1", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("noix-1@Pompe a assembler 1", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Part.TranslateComponent
boolstatus = Part.Extension.SelectByID("", "FACE", -0.08063214430979, -0.005055771715803, -0.01249999999993, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "FACE", 0.00220588303398, 0.007699324973345, 0.02850000000001, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "EDGE", -0.1164548710004, -0.03904313747927, -0.05424607871464, False, 0, Nothing)
' MSGBOX
' Le composant sélectionné est fixé. Il ne peut pas être déplacé.

boolstatus = Part.Extension.SelectByID("", "VERTEX", -0.138, -0.038, -0.045, False, 0, Nothing)
' MSGBOX
' Le composant sélectionné est fixé. Il ne peut pas être déplacé.

Part.ClearSelection
boolstatus = Part.Extension.SelectByID("", "EDGE", -0.06264319356814, -0.0204356293344, -0.01861104249878, False, 0, Nothing)
Part.RotateComponent
boolstatus = Part.Extension.SelectByID("", "EDGE", -0.1442796979073, 0.1238595085181, 0.0272109386849, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "FACE", -0.08101333067043, 0.1562711308056, 0.006855026254982, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "EDGE", 0.0006203475440998, 0.1252919330892, -0.0586644193379, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "VERTEX", -0.2077743062587, -0.1044186090129, 0.1120595399705, False, 0, Nothing)
Part.ViewZoomtofit2
boolstatus = Part.Extension.SelectByID("", "VERTEX", -0.1095894589822, 0.1274283025915, 0.04035939531857, False, 0, Nothing)
Part.TranslateComponent
boolstatus = Part.Extension.SelectByID("", "EDGE", 0.05162227061851, 0.1177597455025, -0.09163612123791, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "EDGE", -0.1380276738384, -0.08053789639814, 0.1398824313807, False, 0, Nothing)
Part.ClearSelection
' MSGBOX
' E:\TP Labo MPSI\Supports\Doshydro\Maquette numérique\Pompe a assembler 1.SLDASM n'a pas été reconstruit avec succès depuis le dernier changement de fonction ou un modèle référencé de l'extérieur a changé.
' 	Il est plus sûr de reconstruire avant d'enregistrer.
' 		Reconstruire maintenant ?

Part.Save2 FALSE
Part.ViewDisplayHiddenremoved
Part.ViewDisplayHiddenremoved
Part.ViewDisplayShaded
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ExitApp
End Sub
